services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: demo_keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Fix the warning for missing hostname in dev mode
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8080:8080"
